### ISSUE TITLE
Consider changing/adding the "u" convension for micro- values?

### ISSUE THREAD

**Issue by T-K-233** [DiegoWang51/hbar#1]
I know that it is not a good practice to represent "μ" as "u", but as far as I know, people would use the letter u to represent micro- values. I think it is better to implement this in this calculator. 

要不要考虑把 micro- 开头的换成 u- 开头的来表示 微 这个数量级？这确实不是一个好习惯，但我觉得这样修改之后会方便很多！

`um * 1000 == 0.001 m` looks much better than `microm * 1000 == 0.001 * m`

`um * 1000 == 0.001 m` 看上去比 `microm * 1000 == 0.001 * m` 好多了！！

**Comment by dw61** [comment]
make sense. microm does look long and ugly.

**Comment by dw61** [comment]
fixed. thanks for your suggestion!!
谢谢tk！
